name    'rcg-tcpwrappers'
version '0.0.1'
source 'https://github.com/sfu-rcg/rcg-tcpwrappers'
author 'rcg'
license 'Simplified BSD License'
summary 'This is a simple tcpwrappers module manage allow/deny rules.'
description 'This is a simple tcpwrappers module manage allow/deny rules.'
project_page 'https://github.com/sfu-rcg/rcg-tcpwrappers'
dependency 'puppetlabs/stdlib', '>= 4.0.0'
dependency 'puppetlabs/concat', '>= 1.0.4'
